apiVersion: extensions/v1beta1
kind: Deployment 
metadata:
   name: pythondeployment1
spec:
   replicas: 1
   selector:
     matchLabels:
       app: pythonfile1
   template:
     metadata:
       labels:
         app: pythonfile1
     spec:
       containers:
       - name: kubecon4
         image: tripathiakhila/kubeim:latest
         imagePullPolicy: Always
