apiVersion: v1.11.4
kind: Deployment 
metadata:
   name: pythondeployment
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: pythonfile
   template:
     metadata:
       labels:
         app: pythonfile
     spec:
       containers:
       - name: myimage
         image: https://cloud.docker.com/repository/docker/tripathiakhila/newproj2
         imagePullPolicy: Always
